import {
  CodeforcesIcon,
  EnvelopeIcon,
  FacebookIcon,
  GithubIcon,
  InstagramIcon,
  LeetcodeIcon,
  LinkedinIcon,
  PhoneIcon,
  WhatsappIcon,
  YouTubeIcon,
} from "@/components/icons";
import { ContactMethodInterface } from "@/types/contact.types";

export const CONTACT_METHODS: Array<ContactMethodInterface> = [
  {
    id: "email",
    label: "Email",
    value: "shakil102043@gmail.com",
    href: "mailto:shakil102043@gmail.com",
    Icon: EnvelopeIcon,
    external: false,
  },
  {
    id: "phone",
    label: "Phone",
    value: "+880 1703374162",
    href: "tel:+8801703374162",
    Icon: PhoneIcon,
    external: false,
  },
  {
    id: "whatsapp",
    label: "Whatsapp",
    value: "01703374162",
    href: "https://wa.me/01703374162",
    Icon: WhatsappIcon,
    external: true,
  },
  {
    id: "linkedin",
    label: "LinkedIn",
    value: "shakil102043",
    href: "https://www.linkedin.com/in/shakil102043/",
    Icon: LinkedinIcon,
    external: true,
  },
  {
    id: "github",
    label: "GitHub",
    value: "developerHub01",
    href: "https://github.com/developerHub01",
    Icon: GithubIcon,
    external: true,
  },
  {
    id: "facebook",
    label: "Facebook",
    value: "abdusshohid.shakil.5",
    href: "https://www.facebook.com/abdusshohid.shakil.5",
    Icon: FacebookIcon,
    external: true,
  },
  {
    id: "instagram",
    label: "Instagram",
    value: "shakil102043",
    href: "https://www.instagram.com/shakil102043/",
    Icon: InstagramIcon,
    external: true,
  },
  {
    id: "youtube",
    label: "YouTube",
    value: "@DeveloperHub1",
    href: "https://www.youtube.com/@DeveloperHub1",
    Icon: YouTubeIcon,
    external: true,
  },
  {
    id: "codeforces",
    label: "Codeforces",
    value: "abdusShohidShakil",
    href: "https://codeforces.com/profile/abdusShohidShakil/",
    Icon: CodeforcesIcon,
    external: true,
  },
  {
    id: "leetcode",
    label: "Leetcode",
    value: "shakil102043",
    href: "https://leetcode.com/u/shakil102043/",
    Icon: LeetcodeIcon,
    external: true,
  },
] as const;
